#  ______ _  __     _______  ______ 
# |  ____| | \ \   / /  __ \|  ____|
# | |__  | |  \ \_/ /| |__) | |__   
# |  __| | |   \   / |  ___/|  __|  
# | |    | |____| |  | |    | |____ 
# |_|    |______|_|  |_|    |______|
#
# Thanks for using FlyPE! All permissions are stated on our page on
# poggit or github! If you have any issues, feel free to let me know at
# https://github.com/AGTHARN/FlyPE/issues or https://discord.gg/bGKEJTKPZc !


##### VERSION #####

# CONFIG VERSION! (DO NOT CHANGE THIS VALUE)
config-version: 5.10

###################


##### LANGUAGE #####

# Default language will be used if a player's language is not available in the list.
# 
# DEFAULT LANGUAGE: en_US
# CURRENT AVAILABLE LANGUAGE CODES: 
#  - en_US [English (US)]
#  - es_ES [Español (España)]
lang: "en_US"

####################


##### DATABASE ######

database:
  # The database type. "sqlite" and "mysql" are supported.
  type: sqlite

  # Edit these settings only if you choose "mysql".
  mysql:
    host: 127.0.0.1
    # Avoid using the "root" user for security reasons.
    username: root
    password: ""
    schema: flype

  # The maximum number of simultaneous SQL queries
  # Recommended: 1 for sqlite, 2 for MySQL. You may want to further increase this value if your MySQL connection is very slow.
  worker-limit: 1

#####################