#  ______ _  __     _______  ______ 
# |  ____| | \ \   / /  __ \|  ____|
# | |__  | |  \ \_/ /| |__) | |__   
# |  __| | |   \   / |  ___/|  __|  
# | |    | |____| |  | |    | |____ 
# |_|    |______|_|  |_|    |______|
#
# Thanks for using FlyPE! All permissions are stated on our page on
# poggit or github! If you have any issues, feel free to let me know at
# https://github.com/AGTHARN/FlyPE/issues or https://discord.gg/bGKEJTKPZc !


##### VERSION #####

# CONFIG VERSION! (DO NOT CHANGE THIS VALUE)
config-version: 5

###################


##### LANGUAGE #####

# Default language will be used if a player's language is not available in the list.
# 
# DEFAULT LANGUAGE: en_US
# CURRENT AVAILABLE LANGUAGE CODES: 
#  - en_US [English (US)]
#  - es_ES [Español (España)]
lang: "en_US"

####################