#  ______ _  __     _______  ______ 
# |  ____| | \ \   / /  __ \|  ____|
# | |__  | |  \ \_/ /| |__) | |__   
# |  __| | |   \   / |  ___/|  __|  
# | |    | |____| |  | |    | |____ 
# |_|    |______|_|  |_|    |______|
#
# Thanks for using FlyPE! All permissions are stated on our page on
# poggit or github! If you have any issues, feel free to let me know at
# https://github.com/AGTHARN/FlyPE/issues or https://discord.gg/KD4Fp8dnZD !


##### PLUGIN INTEGRATION #####

# These settings are to prevent FlyPE from conflicting with other plugins.
# The most likely reason for conflicts is due to particles as they are visible.
# But it can also be due to other reasons as stated for each option.
# 
# NOTE:
# It is fine if you leave these settings set at true even without the plugins.

# CONFLICTED : EVERYTHING
# ACTION     : WARN
blazinfly-integration: true

# CONFLICTED : EVERYTHING
# ACTION     : WARN
betterflight-integration: true

# CONFLICTED : PARTICLES
# ACTION     : ADJUST
vanishv2-integration: true

# CONFLICTED : PARTICLES
# ACTION     : ADJUST
simplelay-integration: true

##############################