--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/AGTHARN/FlyPE
build-by-default: true
branches:
- master
projects:
  FlyPE:
    path: ""
    libs:
    - src: jojoe77777/FormAPI/libFormAPI
      version: ^1.3.0
    - src: JackMD/UpdateNotifier/UpdateNotifier
      version: ^2.1.0
    - src: PresentKim/libtranslator/libtranslator
      version: ^2.1.0
...
