--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/AGTHARN/FlyPE
build-by-default: true
branches:
- master
projects:
  FlyPE:
    path: ""
    icon: icon.png
    libs:
    - src: jojoe77777/FormAPI/libFormAPI
      version: ^1.3
    lint:
        phpstan: false
...
