main: AGTHARN\FlyPE\Main
name: FlyPE
author: AGTHARN
version: 1.0.0
api: [3.0.0, 4.0.0]

depend:
- FormAPI
softdepend:
- EconomyAPI

commands:
  fly:
    permission: "flype.command"
    description: "fly command"

permissions:
  flype.command:
    default: op
  flype.command.others:
    default: op
  flype.command.bypass:
    default: op
