main: AGTHARN\FlyPE\Main
name: FlyPE
author: AGTHARN
version: 5.0.0
api: 4.0.0

permissions:
  flype.command:
    default: op
  flype.command.others:
    default: op
  flype.world.bypass:
    default: false