main: AGTHARN\FlyPE\Main
name: FlyPE
authosr: [AGTHARN, CosmicNebula200]
version: 5.1.0
api: 4.0.0

permissions:
  flype.command:
    default: op
  flype.command.others:
    default: op
  flype.world.bypass:
    default: false