main: AGTHARN\FlyPE\Main
name: FlyPE
author: AGTHARN
version: 3.5.1
api: 3.0.0

softdepend:
- EconomyAPI
- PurePerms # for permissions

permissions:
  flype.command:
    default: op
  flype.command.others:
    default: op
  flype.particles:
    default: op
  flype.effects:
    default: op
  flype.flightspeed:
    default: op
  flype.command.bypass:
    default: false