main: AGTHARN\FlyPE\Main
name: FlyPE
author: AGTHARN
version: 4.1.4
api: 3.0.0

softdepend:
- EconomyAPI # fly ui
- PurePerms # for permissions
- VanishV2 # integration support
- SimpleLay # integration support

permissions:
  flype.command:
    default: op
  flype.command.help:
    default: true
  flype.command.others:
    default: op
  flype.command.tempfly:
    default: op
  flype.command.coupon:
    default: op
  flype.particles:
    default: op
  flype.effects:
    default: op
  flype.flightspeed:
    default: op
  flype.bypass:
    default: false