main: AGTHARN\FlyPE\Main
name: FlyPE
author: AGTHARN
version: 3.2.0
api: 3.0.0

softdepend:
- EconomyAPI

permissions:
  flype.command:
    default: op
  flype.command.others:
    default: op
  flype.particles:
    default: op
  flype.effects:
    default: op
  flype.flightspeed:
    default: op
  flype.command.bypass:
    default: false