main: AGTHARN\FlyPE\Main
name: FlyPE
author: AGTHARN
version: 1.1.0
api: 3.12.0

softdepend:
- EconomyAPI

commands:
  fly:
    permission: "flype.command"
    description: "Fly command to toggle flight"

permissions:
  flype.command:
    default: op
  flype.command.others:
    default: op
  flype.command.bypass:
    default: op
