main: AGTHARN\FlyPE\Main
name: FlyPE
author: AGTHARN
version: 3.0.1
api: 3.0.0

softdepend:
- EconomyAPI

permissions:
  flype.command:
    default: op
  flype.command.others:
    default: op
  flype.command.bypass:
    default: false
