#  ______ _  __     _______  ______ 
# |  ____| | \ \   / /  __ \|  ____|
# | |__  | |  \ \_/ /| |__) | |__   
# |  __| | |   \   / |  ___/|  __|  
# | |    | |____| |  | |    | |____ 
# |_|    |______|_|  |_|    |______|
#

# Thanks for using FlyPE! All permissions are stated on our page on
# poggit or github! If you have any issues, feel free to let me know at
# https://github.com/AGTHARN/FlyPE/issues or https://discord.gg/bGKEJTKPZc!

##### VERSION #####

# CONFIG VERSION! (DO NOT CHANGE THIS VALUE)
config-version: 4.0

###################


##### LANGUAGE #####

# Preset language file to use, set as "default" if you want to modify it in default.yml.
# 
# DEFAULT LANGUAGE: en_US
# CURRENT AVAILABLE LANGUAGE CODES: en_US, es
lang: "en_US"

####################


##### FLY SETTINGS #####

# NOTE: "apply-flight-settings-gmc" configuration will allow settings to be applied for gamemode creative.

# If set to true, fly is disabled when a player joins.
# If set to false, fly wouldn't be disabled when a player joins.
#
# NOTE: Only works when save-flight-state is set to true.
join-disable-fly: false

# If set to true, fly is disabled when a punches another player.
# If set to false, fly wouldn't be disabled when a punches another player.
combat-disable-fly: true

# If set to true, players would be able to drop items while they are in flight mode.
# If set to false, players would NOT be able to drop items while they are in flight mode.
item-dropping: true

# If set to true, players would be able to pick up items while they are in flight mode.
# If set to false, players would NOT be able to pick up items while they are in flight mode.
picking-up-items: true

# If set to true, players would be able to break blocks while they are in flight mode.
# If set to false, players would NOT be able to break blocks while they are in flight mode.
block-breaking: true

# If set to true, players would be able to place blocks while they are in flight mode.
# If set to false, players would NOT be able to place blocks while they are in flight mode.
block-placing: true

# If set to true, players would be able to eat while they are in flight mode.
# If set to false, players would NOT be able to eat while they are in flight mode.
player-eating: true

#######################


##### FLY STATE #####

# Whether or not to save flight state when a player leaves.
save-flight-state: true

#####################


##### FLY SPEED #####

# Enable fly speed modification.
#
# NOTE:
# This may be buggy. Use with caution.
fly-speed-mod: false

# Multiplies the current fly speed.
# 
# NOTE:
# THE LIMIT IS 3 BECAUSE OF THE LIMITED RANGE. 
# AN InvalidArgumentException WILL BE THROWN IF IT IS OVER 3.4!
# I SUGGEST THAT IT SHOULD BE SET TO A MAXIMUM OF 2 INSTEAD!
fly-speed: 1

# Flight speed check rate. The faster it is, the less buggy it is and more performance consuming.
# 20 (ticks) = 1 second
fly-speed-check-rate: 20

# If set to true, players in gamemode creative will have the speed modification.
# If set to false, players in gamemode creative will NOT have the speed modification.
fly-speed-creative: false

#####################


##### FLY UI #####

# If set to true, a UI would show up when a player runs the /fly command.
# If set to false, everything would be normal and players would be able to toggle flight normally.
enable-fly-ui: false

# If set to true and enable-fly-ui is set to true, players would have to pay to enable fly. (NOTE THAT YOU NEED THE ECONOMYAPI PLUGIN)
# If set to true and enable-fly-ui is set to false, everything would be normal and player would be able to toggle flight.
# If set to false and enable-fly-ui is set to true, players would NOT have to pay for fly.
pay-for-fly: false

# If payforfly is set to true, set this to the amount of money a player needs to pay for fly. (1800, 4500, 8500 etc.)
buy-fly-cost: 100000

# If set to true and pay-for-fly is set to true, purchasing flight would be saved.
# If set to false and pay-for-fly is set to true, purchasing flight would NOT be saved.
save-purchased-data: true

##################

# If set to true, the texts on the UI will be editable by the configurations below.
# If set to false, the default texts would be used.
custom-ui-texts: false

# The title that is located at the top of the UI.
fly-ui-title: "§l§7< §6FlyUI §7>"

# The toggle fly button.
# {cost} = Cost of flight.
fly-ui-toggle: "§aToggle Fly"

# The exit button.
fly-ui-exit: "§cExit"

##################


##### PARTICLES #####

# If set to true, particles will appear on player's feet if they are flying.
# If set to false, no particles will appear.
enable-fly-particles: false

# Type of particle to spawn. Default: FlameParticle.
# 
# SUPPORTED: (case insensitive)
# BubbleParticle, CriticalParticle, EnchantParticle, InstantEnchantParticle, ExplodeParticle, HugeExplodeParticle
# EntityFlameParticle, FlameParticle, HeartParticle, InkParticle, LavaDripParticle, LavaParticle, PortalParticle
# RedstoneParticle, SmokeParticle, SplashParticle, SporeParticle, MobSpawnParticle, WaterDripParticle
# WaterParticle, EnchantmentTableParticle, HappyVillagerParticle, AngryVillagerParticle, RainSplashParticle
# BlockForceFieldParticle, DestroyBlockParticle, SnowballPoofParticle
fly-particle-type: "FlameParticle"

# Rate of fly particle.
# 20 (ticks) = 1 second
fly-particle-rate: 5

# Only change the configuration below if you're using the DestroyBlockParticle.
particle-block-id: 1

#####################


##### EFFECTS #####

# If set to true, players will get effects if they are flying.
# If set to false, no effects will be given.
enable-fly-effects: false

# Type of effect to be given. Default: HASTE.
#
# SUPPORTED: (case insensitive)
# SPEED, SLOWNESS, HASTE, MINING_FATIGUE, STRENGTH, INSTANT_HEALTH, INSTANT_DAMAGE, JUMP_BOOST
# NAUSEA, REGENERATION, RESISTANCE, FIRE_RESISTANCE, WATER_BREATHING, INVISIBILITY, BLINDNESS
# NIGHT_VISION, HUNGER, WEAKNESS, POISON, WITHER, HEALTH_BOOST, ABSORPTION, SATURATION
# LEVITATION, FATAL_POISON, CONDUIT_POWER
effect-type: HASTE

# The amplifier is a value that increases the level of the effect.
effect-amplifier: 1

# If set to true, particles from the effects will be visible.
# If set to false, particles from the effects will be visible.
effect-visible: true

# Rate of fly effect check.
# 20 (ticks) = 1 second
fly-effect-check-rate: 20

##################


##### INTEGRATIONS #####

# It is fine if you set the values to true even though you don't have the plugins.

# If set to true, players that are hidden from VanishV2 will NOT show the particles and effects.
# If set to false, particles and effects will always show.
#
# VERSION SUPPORTED: 1.15
vanishv2-support: true

# If set to true, effects and particles underneath will be removed.
# If set to false, effects and particles underneath are shown.
#
# VERSION SUPPORTED: 2.1.0
simplelay-support: true

########################


##### FLIGHT COUPON #####

# If set to true, players will be able to use the flight coupon.
# If set to true, players will NOT be able to use the flight coupon.
enable-coupon: false

# The item texture of the flight coupon. (only applies to newer coupons)
coupon-item-id: 339

# The name of the flight coupon.
coupon-name: "&6Flight Coupon"

# If set to true, the flight coupon will be obtainable in the creative mode item list.
# If set to false, the flight coupon will NOT be obtainable in the creative mode item list.
coupon-creative-item: true

# If set to true, running the flight command will give the player a flight coupon.
# If set to false, running the flight command will NOT give the player a flight coupon.
coupon-command-toggle-item: true

#########################


##### FLIGHT TOGGLE COOLDOWN #####

# If set to true, players will NOT be allowed to toggle flight until a number of seconds have passed.
# If set to false, players will be allowed to toggle flight anytime.
#
# NOTE: Recommended to be set to true.
enable-cooldown: true

# The number of seconds the cooldown will last.
cooldown-seconds: 10

# If set to true, players will receive a message when the number of seconds have NOT passed after their last use.
# If set to false, players will NOT receive any message.
send-cooldown-message: true

##################################


##### CREATIVE MODE ######

# If set to true, players that fly and are in gamemode creative will have effects applied to them.
# If set to false, players that fly and are in gamemode creative will NOT have effects applied to them.
creative-mode-effects: false

# If set to true, players that fly and are in gamemode creative will have particles applied to them.
# If set to false, players that fly and are in gamemode creative will NOT have particles applied to them.
creative-mode-particles: false

# If set to true, players that run /fly and are in gamemode creative will be allowed to toggle their flight.
# If set to false, players that run /fly and are in gamemode creative will NOT be allowed to toggle their flight.
allow-toggle-flight-gmc: false

# If set to true, players that are in gamemode creative will have fly settings applied to them.
# If set to false, players that are in gamemode creative will NOT have fly settings applied to them.
#
# NOTE: USE WITH CAUTION
apply-flight-settings-gmc: false

##########################


##### TOGGLE FLIGHT SOUND #####

# If set to true, after flight is enabled/disabled, a sound will be played.
# If set to false, after flight is enabled/disabled, nothing will be played.
enable-fly-sound: true

# Type of sound to be played after flight is enabled. Default: PopSound.
#
# SUPPORTED: (case insensitive)
# AnvilBreakSound, AnvilFallSound, AnvilUseSound, BlazeShootSound, ClickSound, DoorBumpSound
# DoorCrashSound, DoorSound, EndermanTeleportSound, FizzSound, GhastShootSound, GhastSound
# LaunchSound, PopSound
fly-enabled-sound: "PopSound"

# Type of sound to be played after flight is disabled. Default: PopSound.
#
# SUPPORTED: (case insensitive)
# AnvilBreakSound, AnvilFallSound, AnvilUseSound, BlazeShootSound, ClickSound, DoorBumpSound
# DoorCrashSound, DoorSound, EndermanTeleportSound, FizzSound, GhastShootSound, GhastSound
# LaunchSound, PopSound
fly-disabled-sound: "PopSound"

###############################


##### TEMPORAL FLY #####

# If set to true, players that toggle flight using the tempflight subcommand will be timed.
# If set to false, players that toggle flight using the tempflight subcommand will NOT be timed.
time-fly: false

########################


##### BLACKLIST OR WHITELIST WORLDS #####

# If set to blacklist, players that are in the worlds listed in blacklisted-worlds wouldn't be able to run the fly command.
# If set to whitelist, players that are in the worlds listed in whitelisted-worlds would be able to run the fly command.
mode: blacklist

# (BLACKLIST) These worlds only apply if the mode is set to blacklist.
blacklisted-worlds:
 - "noflyworld1"
 - "noflyworld2"
 - "noflyworld3"
 
# (WHITELIST) These worlds only apply if the mode is set to whitelist.
whitelisted-worlds:
 - "flyworld1"
 - "flyworld2"
 - "flyworld3"

# Toggle message when a player moves to a world that restricts flight.
level-change-restricted: true

# Toggle message when a player moves to a world that does NOT restrict flight.
level-change-unrestricted: false
 
#########################################